# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4553c23db47ff4b4d0fdafc0a6d0dea017ea4cb326a5b46025b234e24fb7375d912a383fb775a56ef745c8f94970446a2605546120ad216f5b3c9b282f7d6b2e

test:
  secret_key_base: 10257cfef22b76618e2bd0e72abe114ee4d939ef6380e74f1f9998dfe84cfc74f59f4341ec95cebc4fa680fa03b2a29d23361f3d7391a8026f636067971b21e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
